# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      
    - name: Create .env
      env:
        ENV_NAME: ${{ secrets.ENV_NAME }}
        ENV: ${{ secrets.ENV }}
      run: |
        touch ./$ENV_NAME
        echo "$ENV" > ./$ENV_NAME
    - name: Build
      run: |
        yarn add next
        npm install -save next --legacy-peer-deps
        CI=false npm run build
      shell: bash
